### ISSUE TITLE
Add option to select attachment path separator in the resulting xml file

### ISSUE THREAD

**Issue by mikhail-g** [testspace-com/cypress-xml-reporter#22]
When using the plugin to generate test reports of junit format to use in GitLab CI
And the tests are executed on Windows machine the tag is generated:
```
<system-out>[[ATTACHMENT|cypress\screenshots\myTest.spec.ts\my test suite -- my test case (failed).png]]</system-out>
```
But GitLab CI needs slashes `/` instead of back slashes `\` in the attachment path to have a valid link
GitLabs applies ANSII encoding of the report content `\` => `%5C` and as a result have this king of link with the path from the xml report file having encoded back-slashes. The link i not working:
```
https://gitlab.mycompany.com/myproject/-/jobs/123123/artifacts/file/cypress%5Cscreenshots%5CmyTest.spec.ts%5Cmy%20test%20suite%20--%20my%20ctest%20case%20(failed).png
```
But if the back slashes are changed to normal slashes, they are encoded `/` => `%2F` and the resulting link is working:
```
https://gitlab.mycompany.com/myproject/-/jobs/123123/artifacts/file/cypress%2Fscreenshots%2FmyTest.spec.ts%2Fmy%20test%20suite%20--%20my%20ctest%20case%20(failed).png
```

Please add attachment path separator to reporterOption that would be used for generating the attachment path in the report file. But for checking if the file exists in the filesystem the standard path.sep will be used still

**Comment by munderseth** [comment]
@mikhail-g this issue has been resolved now.

**Comment by mikhail-g** [comment]
Thank you @munderseth !
